### ISSUE TITLE
Animation Set is not being saved for new imported buildings

### ISSUE THREAD

**Issue by SpagoAsparago** [kingdom-of-ds-hacking/CTRMapV#2]
When a building is added from the building editor as well as a new animation, the default is *1 set/4 animations*, but after changing it to *2 sets/1+1 animation*, committing changes and reopening the building editor it's again back to *1 set/4 animations*

It doesn't seem to work in game either as my door animation only triggers when exiting a building and not when entering.

I attached the dae containing the model and animation imported 
[customdoor.zip](https://github.com/kingdom-of-ds-hacking/CTRMapV/files/11655729/customdoor.zip)

**Comment by HelloOO7** [comment]
Thanks for the report. Two things:
- One part of this problem is a UI bug in the editor that made it so that upon changing the animation set layout, the animation set dropdown wasn't updated with the new animation set options. That should now be fixed - please try with the builds in here: https://drive.google.com/drive/folders/1As212Darx_IWzkgo--ym7RzyyZPXhXZ5?usp=sharing
- Due to this UI bug, it might be now that it is fixed handy to know (not saying you don't already, but it's likely) that the animation set layout is not really a _thing_ in the game - it's a virtual concept that only exists for user convenience once a resource is selected and disappears once you click away from it (it does affect the import order but just clicking the dropdown does effectively nothing). It is then derived from the layout of animations actually present in the resource, which means that if you only import one animation, it will default to 1x4, since that's the most logical schema for it. If you choose 2x1, the "change" (keep in mind that it is purely visual and has no actual effect) will only persist if you actually proceed to import the two animations into the two slots. You couldn't do that before because of the UI bug, but now you can, by importing the two animations (or one animation twice) into the two separate animation sets that appear when you change the layout to 2x1.

**Comment by SpagoAsparago** [comment]
Thanks again for your work and the explanation. Now it seems I can import the animations correctly, I'll close the issue.
