### ISSUE TITLE
NSBCAs are incorrectly written from DAE

### ISSUE THREAD

**Issue by BromBromBromley** [kingdom-of-ds-hacking/CTRMapV#4]
When importing a model and animation from Blender that was exported as a COLLADA file, the animation initially plays back correctly. However, if I test the animation written to an NSBCA with the written NSBMD, the animation is rotated -90 degrees on the x-axis along with some bones being seemingly translated incorrectly. Even if I export the DAE from Creative Studio and import it as a DAE, while it looks okay there, once the animation becomes an NNS animation, it doesn't look correct anymore. I've attached the CTRMap generated DAE along with the CMIF, NSBMD, and NSBCA files.
[gym_rep.zip](https://github.com/kingdom-of-ds-hacking/CTRMapV/files/12889806/gym_rep.zip)

**Comment by HelloOO7** [comment]
Most of these seem to be cosmetic issues - as in, the data in the file is written correctly, but the importer reads it wrong. Anyhow, you can verify whether using [this build of the plug-in](https://drive.google.com/file/d/1JMm8iCMVbb9W5HLwRH2Pv5GD3rfalQMr/view?usp=sharing) makes it import and display properly.

However, there is also an issue with your model; that is, it has multiple root bones, which I'm almost positive is a phenomenon that is not present anywhere in the original games, and if such a skeleton is compiled into a DS model binary, it could produce undefined behavior because the root matrix is only ever calculated once. There are obviously ways to work around that in the exporter, but I don't plan on implementing them, so I'd strongly recommend to only use one root bone.

**Comment by BromBromBromley** [comment]
Ah, my apologies for misdiagnosing the issue! The build you sent makes it display correctly. Also, thanks for making me aware of the issue of multiple root bones, I'll make sure to fix that.

Also, this is unrelated, but how exactly would one go about making NSBTP animations to display on a model? Trying to make a new material animation using the texture index for the target coordinates doesn't appear to do what I want.

**Comment by HelloOO7** [comment]
I think that is the only way to make CreativeStudio animations unless you want to make your own editor for the IFMA format. However, I don't recall there ever being a NSBTP exporter...

**Comment by BromBromBromley** [comment]
Basically when I've tried to do that method with the texture index in particular, the display would stop redrawing outside of parts where it'd change from an inactive element to an active one. The texture name field never properly populates and changing the texture index even with a non-zero frame length isn't effective. The translation tools seem to work okay, though. Apologies for the poor phrasing.

**Comment by HelloOO7** [comment]
I haven't really used the material animation tool for anything but viewing the animation data for debugging purposes, but if you do feel like you'd find a use for it, you can collect logs and submit an issue detailing the incorrect behavior in the [CE](github.com/kingdom-of-ds-hacking/CTRMap-CE) repo for CreativeStudio.

Just a heads up, though, as I said before, you won't be able to export these animations into NSBTP anyway (unless you make your own export plug-in), so it's up to you whether you deem it fruitful to debug all that given its relative uselessness with the current format support.

**Comment by BromBromBromley** [comment]
Ah, all right. I'll close the issue for now since the main problem has been resolved. Thanks again for your help!
