### ISSUE TITLE
Support for NDS-specific material settings in Creative Studio?

### ISSUE THREAD

**Issue by BromBromBromley** [kingdom-of-ds-hacking/CTRMapV#9]
This isn't anything urgent, but I think it would be nice being able to edit some DS-specific material settings that are missing in Creative Studio, notably:
- Polygon ID (used for alpha sorting and edge marking groups)
- Polygon alpha (this gets occasionally used for setting transparency without explicitly using something like an A3I5 or A5I3 texture)
- Fog enabled flag
While there are more NDS specific things out there (which can be seen with the [NNS Blender Plugin](https://github.com/jellees/nns-blender-plugin)), I think these are some of the more important ones to be able to edit, especially since there is no imd file that can be edited to change these parameters.

**Comment by HelloOO7** [comment]
Those are all very good suggestions.

The fog flag is not supported at the moment because CreativeStudio does not render fog. It can definitely be added as an extra attribute that just "does nothing".

Polygon IDs are technically supported through stencil testing. I think they were only ever propagated to the 3DS formats (using the helper tab for edge group IDs), but it should be a non-breaking change to add them to DS formats too.

Polygon alpha is natively supported using vertex color alpha or Nitroshader. It is undocumented how to actually make it take effect though. If you have a model that was imported from NSBMD, it should be ready to go. Nitroshader uses constant color 5 of the 3DS rendering pipeline to store the polygon alpha value. So if your model is using this constant color, it is all set up for you. Otherwise, such as if you are importing DAE, the polygon alpha should be computed as the average of the mesh's vertex color alpha values. If this does not happen, feel free to open a separate issue.

**Comment by HelloOO7** [comment]
All of these should now be supported in the latest releases.

**Comment by BromBromBromley** [comment]
Amazing! This is great to hear! I'll try to test them out soon.

Happy holidays by the way!

**Comment by BromBromBromley** [comment]
When inspecting the NSBMD generated by CreativeStudio after setting the edge group ID, it doesn't seem like the changes actually get written. Reimporting the NSBMD within CreativeStudio along with viewing the Polygon ID in EveryFileExplorer shows that the Polygon ID does not get set unless it is a translucent material for sorting purposes.

**Comment by HelloOO7** [comment]
Are you sure you have set everything up correctly?
For my testing scenario, I imported one of the cutscene models from BW2, changed the polygon ID (stencil test reference) to 42 and re-saved as NSBMD and that worked alright.
Bear in mind that the stencil test reference is not taken as valid unless the setting of stencil operations is configured in the same way as it is in the DS fixed-function hardware. There is a button in the "Shortcuts" tab that does it for you, in case you are making an all-new material, or you can import an existing NDS material as IFMT to be sure.

**Comment by BromBromBromley** [comment]
I was making use of the shortcuts tab, but it seems that it sets the test mask and buffer mask to 255 instead of 31. Looking at the code for `isNshStencilSchemeUsed()` it seems that it needs the masks to be set to 31, so I will try setting the polygon ID using the stencil test reference instead of through the shortcuts menu instead and report back.

**Comment by BromBromBromley** [comment]
OK, setting it through the stencil test reference setting appeared to work correctly!

So it seems there is an issue with setting it through the shortcuts tab due to it changing the test and buffer masks.

**Comment by HelloOO7** [comment]
Indeed, the mask must be 31 as that is the bit width that the NDS uses.

Are you using the "Set up NDS shader" button?

The "edge ID" button, or something like that, is historical and is intended for 3DS games.

**Comment by BromBromBromley** [comment]
I did previously, but I clicked it after setting the edge ID and it seems to overwrite the old stencil reference with 0, so perhaps that caused the appearance of it not functioning it properly.

**Comment by HelloOO7** [comment]
Yes, the edge ID setting overrides the stencil test, as the configuration (which is technologically identical to the DS scheme) needs to be set up properly for the 3DS materials which this feature was intended for.

Similarly, the NDS shader setup overrides the stencil test reference, since it attempts to mimic the NDS rendering hardware using the 3DS pipeline, which CS runs on.

The proper course of action is therefore to use the Shortcuts tab to prepare the material for use with NDS as the first order of business, then edit the stencil test reference as needed afterwards.

**Comment by BromBromBromley** [comment]
I see, thank you for the support.

Do you know if there is any way to set the color for the edge marking? I'm uncertain if this is an attribute of the model itself or if this is something handled in software like the toon or reflectivity table.

**Comment by HelloOO7** [comment]
This is handled using the EDGE_COLOR register of the GPU. It allows for setting a color for certain ranges of the polygon IDs. However, since this is pretty much a stencil operation, it can only be (meaningfully) set once per rendering pass. I think the game uses some external file to set these probably.

It also seems that given how many colors it supports, the polygon ID is 6-bit and not 5-bit as I remembered it, so I'll fix that in the core library when I get to it eventually.

**Comment by BromBromBromley** [comment]
I see. Thanks again!
